# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIdQtrhdIrHYKi1tA_HnXrQFtE1xgdqK

Import Libraries
"""

import torchvision
from torchvision.transforms import transforms
from torchvision import datasets

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt
import random
import numpy as ns
import os
import time

os.makedirs(".images/gan",exist_ok=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

"""**HyperParameter**"""

batch_size = 64
num_epochs = 30
image_size = 64
latent_dim = 100
print_every = 5
n_show = 1

transforms = transforms.Compose([
    transforms.Resize(image_size),
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

data = datasets.CIFAR10(".data",train=True,download=True,transform=transforms)

data

iterator = DataLoader(data, batch_size=batch_size,shuffle=True)

len(iterator)

"""Generative"""

class Generator(nn.Module):
  def __init__(self, latent_dim, image_size):
    super().__init__()

    self.main = nn.Sequential(
        nn.ConvTranspose2d(in_channels=latent_dim,
                           out_channels=image_size * 8,
                           kernel_size=4,
                           stride=1,
                           padding=0,
                           bias=False
                           ), # (512, 4, 4)
        nn.BatchNorm2d(image_size * 8),
        nn.ReLU(inplace=True),

        nn.ConvTranspose2d(in_channels=image_size * 8,
                           out_channels=image_size * 4,
                           kernel_size=4,
                           stride=2,
                           padding=1,
                           bias=False
                           ),#(256, 8, 8)
        nn.BatchNorm2d(image_size * 4),
        nn.ReLU(inplace=True),

        nn.ConvTranspose2d(in_channels=image_size * 4,
                           out_channels=image_size * 2,
                           kernel_size=4,
                           stride=2,
                           padding=1,
                           bias=False
                           ),#(128, 16, 16)
        nn.BatchNorm2d(image_size * 2),
        nn.ReLU(inplace=True),

        nn.ConvTranspose2d(in_channels=image_size * 2,
                           out_channels=image_size,
                           kernel_size=4,
                           stride=2,
                           padding=1,
                           bias=False
                           ),#(64,32,32)
        nn.BatchNorm2d(image_size),
        nn.ReLU(inplace=True),

        nn.ConvTranspose2d(in_channels=image_size,
                           out_channels=3,
                           kernel_size=4,
                           stride=2,
                           padding=1,
                           bias=False),#(3, 64, 64)
        nn.Tanh()
    )

  def forward(self,x):
    return self.main(x)

"""Discriminator"""

class Discriminator(nn.Module):
  def __init__(self, image_size):
    super().__init__()
    self.main = nn.Sequential(
        nn.Conv2d(in_channels=3,
                  out_channels=image_size,
                  kernel_size=4,
                  stride=2,
                  padding=1,
                  bias=False
                  ), #(image_size, 32, 32)
        nn.LeakyReLU(0.2,inplace=True),

        nn.Conv2d(in_channels=image_size,
                  out_channels=image_size*2,
                  kernel_size=4,
                  stride=2,
                  padding=1,
                  ), #(image_size * 2,16 ,16)
        nn.BatchNorm2d(image_size*2),
        nn.LeakyReLU(0.2,inplace=True),

        nn.Conv2d(in_channels=image_size*2,
                  out_channels=image_size*4,
                  kernel_size=4,
                  stride=2,
                  padding=1,
                  ), #image_size(image_size * 4, 8, 8)
        nn.BatchNorm2d(image_size*4),
        nn.LeakyReLU(0.2),

        nn.Conv2d(in_channels=image_size*4,
                  out_channels=image_size*8,
                  kernel_size=4,
                  stride=2,
                  padding=1,
                  ), #(image_size * 2, 4, 4)
        nn.BatchNorm2d(image_size*8),
        nn.LeakyReLU(0.2,inplace=True),

        nn.Conv2d(in_channels=image_size*8,
                  out_channels=1,
                  kernel_size=4,
                  stride=1,
                  padding=0,
                  bias=False
                  ), #(1,1)
    )

  def forward(self, x):
    return self.main(x).view(-1,1).squeeze(1)

G = Generator(latent_dim, image_size).to(device)
D = Discriminator(image_size).to(device)

def weights_init(m):
    classname = m.__class__.__name__

    if classname.find('Conv') != -1:
        if hasattr(m, 'weight') and m.weight is not None:
            m.weight.data.normal_(0.0, 0.02)

    elif classname.find('BatchNorm') != -1:
        if hasattr(m, 'weight') and m.weight is not None:
            m.weight.data.normal_(1.0, 0.02)
        if hasattr(m, 'bias') and m.bias is not None:
            m.bias.data.fill_(0)

G.apply(weights_init)

D.apply(weights_init)

"""Loss Function

"""

criterion = nn.BCEWithLogitsLoss()

"""**Optimizer**"""

G_optim = optim.Adam(G.parameters(), lr=0.0001, betas=(0.5, 0.9999))

D_optim = optim.Adam(D.parameters(), lr=0.0002, betas=(0.5, 0.9999))

"""**Label**"""

D_loss = []
G_loss = []

"""function time"""

def epoch_time(start_time, end_time):
  elapsed_time = end_time - start_time
  elapsed_min = int(elapsed_time / 60)
  elapsed_secs = int(elapsed_time - (elapsed_min * 60))
  return elapsed_min, elapsed_secs

for epoch in range(1,num_epochs+1):
  start_time = time.time()
  Dl = 0
  Gl = 0
  for x,_ in iterator:
    #train Discriminator
    x = x.to(device)
    x = x.view(-1,3,image_size,image_size)
    z = torch.randn(x.shape[0], latent_dim, 1, 1).to(device)
    real = (torch.ones(x.shape[0],) * 0.9).to(device)
    fake = (torch.zeros(x.shape[0],) * 0.1).to(device)
    with torch.no_grad():
      generated_images = G(z)
    pred_real = D(x) #(batch_size, 1)
    D_error_real = criterion(pred_real, real)

    pred_fake = D(generated_images.detach())
    D_error_fake = criterion(pred_fake, fake)

    D_error = D_error_real + D_error_fake
    D_optim.zero_grad()
    D_error.backward()
    D_optim.step()
    Dl += D_error.item()

    #train Generator
    for _ in range(2):
      G_optim.zero_grad()
      z = torch.randn(x.shape[0], latent_dim, 1, 1).to(device)
      generated_images = G(z)
      pred_fake = D(generated_images)
      G_error = criterion(pred_fake, real)
      G_error.backward()
      G_optim.step()
      Gl += G_error.item()/2


  end_time = time.time()
  elapsed_min, elapsed_secs = epoch_time(start_time, end_time)

  D_loss.append(Dl/len(iterator))
  G_loss.append(Gl/len(iterator))

  if epoch % print_every == 0:

    z = torch.randn(n_show * n_show, latent_dim, 1, 1).to(device)

    with torch.no_grad():
      generated_images = G(z)

    generated_images = generated_images.view(-1, 3, 64, 64) #(batch_size, 1 ,64, 64)

    print(f"Epoch: {epoch:03} |G_loss: {Gl/len(iterator):.03f} |D_loss: {Dl/len(iterator):.03f} | Time: {elapsed_min}m {elapsed_secs}s")

    torchvision.utils.save_image(generated_images, f".images/gan/epoch{epoch:03}.png",nrow=n_show,normalize=True)

    #display images
    img = plt.imread(f".images/gan/epoch{epoch:03}.png")
    plt.imshow(img)
    plt.show()

plt.figure(figsize=(8,5))

plt.plot(D_loss, label="Discriminator Loss")
plt.plot(G_loss, label="Generator Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("GAN Training Loss")
plt.legend()

plt.show()

